@startuml

class WebSiteApplication{
    name: String
    author: String
    js: String
    css: String
    path: String

    + getUserInput()
    + createFiles(path, name, author, js, css)

}

WebSiteApplication ..|> FileGenerator

class FileGenerator{
    htmlContent: String

    + createFiles()
    + createParentDirectory()
    + createIndexHtmlFile()
    + createJavaScriptDirectory()
    + createCSSDirectory()
}
@enduml