@startuml

class WordFreqFinderApplication{
    inputPath: String
    String[] wordsArray
    Map<String, Integer> freqMap

   + readFileAsStringArrayOfWords(inputPath)
   + createMap(wordsArray)
   + sortByValue(freqMap)
}

WordFreqFinderApplication ..|> InputFile

class InputFile{
    + readFileAsStringArrayOfWords()
}

@enduml