@startuml

class ParsingApplication{
    String inputPath
    List<String[]> csvLines

    + readContent(inputPath)
    + createFormattedString(csvLines)
}

ParsingApplication ..|> ReadFile

class ReadFile{
    + readContent()
    + createFormattedString()

}
@enduml